# Generated by Django 5.2.4 on 2026-06-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookidoo_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("prep_time_min", models.IntegerField()),
                ("is_meat", models.BooleanField(default=False)),
                ("last_suggested", models.DateField(blank=True, null=True)),
                ("last_selected", models.DateField(blank=True, null=True)),
                ("times_selected", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DayAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mo", "Mo"),
                            ("Mi", "Mi"),
                            ("Do", "Do"),
                            ("Fr", "Fr"),
                            ("Sa", "Sa"),
                            ("So", "So"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mealplanner.recipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklySelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("feedback_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipes",
                    models.ManyToManyField(
                        through="mealplanner.DayAssignment", to="mealplanner.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dayassignment",
            name="selection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mealplanner.weeklyselection",
            ),
        ),
    ]
