# Generated by Django 5.2.4 on 2026-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="prep_time_min",
            new_name="active_time_min",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_meat",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("meat", "Fleisch"),
                    ("fish", "Fisch"),
                    ("veggie", "Vegetarisch"),
                ],
                default="veggie",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="in_rotation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="kcal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein_g",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_time_min",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
