# Generated by Django 5.2.4 on 2026-06-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0002_rename_prep_time_min_recipe_active_time_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayassignment",
            name="day",
            field=models.CharField(
                choices=[
                    ("Mo", "Montag"),
                    ("Mi", "Mittwoch"),
                    ("Do", "Donnerstag"),
                    ("Fr", "Freitag"),
                    ("Sa", "Samstag"),
                    ("So", "Sonntag"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="WeeklyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(unique=True)),
                ("feedback_text", models.TextField(blank=True)),
                ("reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested",
                    models.ManyToManyField(
                        blank=True, related_name="suggested_in", to="mealplanner.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dayassignment",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="mealplanner.weeklyplan",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="dayassignment",
            unique_together={("plan", "day")},
        ),
        migrations.RemoveField(
            model_name="dayassignment",
            name="selection",
        ),
        migrations.DeleteModel(
            name="WeeklySelection",
        ),
    ]
