# Generated by Django 5.2.4 on 2026-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0003_alter_dayassignment_day_weeklyplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_candidate",
            field=models.BooleanField(default=False),
        ),
    ]
