# Generated by Django 5.2.4 on 2026-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0004_recipe_is_candidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyplan",
            name="selected",
            field=models.ManyToManyField(
                blank=True, related_name="selected_in", to="mealplanner.recipe"
            ),
        ),
    ]
