# Generated by Django 5.2.4 on 2026-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0005_weeklyplan_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyplan",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
