# Generated by Django 5.2.4 on 2026-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplanner", "0006_weeklyplan_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyplan",
            name="awaiting_feedback",
            field=models.BooleanField(default=False),
        ),
    ]
